# Generated by Django 5.0.6 on 2025-07-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membersandfocus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem1_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem2_prob5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
