# Generated by Django 5.0.6 on 2025-07-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membersandfocus_mem1_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa1_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa2_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa3_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa4_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa5_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='fa6_prob9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='high_level_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem3_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem4_prob5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_prob1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_prob2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_prob3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_prob4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membersandfocus',
            name='mem5_prob5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
