# Generated by Django 5.0.6 on 2025-07-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_membersandfocus_fa1_prob1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_to_investigate', models.TextField(blank=True, default='')),
                ('prob1', models.TextField(blank=True, default='')),
                ('cause1', models.TextField(blank=True, default='')),
                ('assumptions1', models.TextField(blank=True, default='')),
                ('difficulty1', models.TextField(blank=True, default='')),
                ('impact1', models.TextField(blank=True, default='')),
                ('prob2', models.TextField(blank=True, default='')),
                ('cause2', models.TextField(blank=True, default='')),
                ('assumptions2', models.TextField(blank=True, default='')),
                ('difficulty2', models.TextField(blank=True, default='')),
                ('impact2', models.TextField(blank=True, default='')),
                ('prob3', models.TextField(blank=True, default='')),
                ('cause3', models.TextField(blank=True, default='')),
                ('assumptions3', models.TextField(blank=True, default='')),
                ('difficulty3', models.TextField(blank=True, default='')),
                ('impact3', models.TextField(blank=True, default='')),
                ('prob4', models.TextField(blank=True, default='')),
                ('cause4', models.TextField(blank=True, default='')),
                ('assumptions4', models.TextField(blank=True, default='')),
                ('difficulty4', models.TextField(blank=True, default='')),
                ('impact4', models.TextField(blank=True, default='')),
                ('prob5', models.TextField(blank=True, default='')),
                ('cause5', models.TextField(blank=True, default='')),
                ('assumptions5', models.TextField(blank=True, default='')),
                ('difficulty5', models.TextField(blank=True, default='')),
                ('impact5', models.TextField(blank=True, default='')),
                ('prob6', models.TextField(blank=True, default='')),
                ('cause6', models.TextField(blank=True, default='')),
                ('assumptions6', models.TextField(blank=True, default='')),
                ('difficulty6', models.TextField(blank=True, default='')),
                ('impact6', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
