# Generated by Django 5.0.6 on 2025-07-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opportunitydiscovery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause1',
            new_name='causes1',
        ),
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause2',
            new_name='causes2',
        ),
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause3',
            new_name='causes3',
        ),
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause4',
            new_name='causes4',
        ),
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause5',
            new_name='causes5',
        ),
        migrations.RenameField(
            model_name='opportunitydiscovery',
            old_name='cause6',
            new_name='causes6',
        ),
    ]
