# Generated by Django 5.0.6 on 2025-07-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_cause1_opportunitydiscovery_causes1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_customer', models.TextField(blank=True, default='')),
                ('users_and_problem1', models.TextField(blank=True, default='')),
                ('functional_need1', models.TextField(blank=True, default='')),
                ('emotional_need1', models.TextField(blank=True, default='')),
                ('severity1', models.TextField(blank=True, default='')),
                ('existing_solution1', models.TextField(blank=True, default='')),
                ('ranking1', models.TextField(blank=True, default='')),
                ('users_and_problem2', models.TextField(blank=True, default='')),
                ('functional_need2', models.TextField(blank=True, default='')),
                ('emotional_need2', models.TextField(blank=True, default='')),
                ('severity2', models.TextField(blank=True, default='')),
                ('existing_solution2', models.TextField(blank=True, default='')),
                ('ranking2', models.TextField(blank=True, default='')),
                ('users_and_problem3', models.TextField(blank=True, default='')),
                ('functional_need3', models.TextField(blank=True, default='')),
                ('emotional_need3', models.TextField(blank=True, default='')),
                ('severity3', models.TextField(blank=True, default='')),
                ('existing_solution3', models.TextField(blank=True, default='')),
                ('ranking3', models.TextField(blank=True, default='')),
                ('users_and_problem4', models.TextField(blank=True, default='')),
                ('functional_need4', models.TextField(blank=True, default='')),
                ('emotional_need4', models.TextField(blank=True, default='')),
                ('severity4', models.TextField(blank=True, default='')),
                ('existing_solution4', models.TextField(blank=True, default='')),
                ('ranking4', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
