# Generated by Django 5.0.6 on 2025-07-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userneed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_state1', models.TextField(blank=True, default='')),
                ('desired_state1', models.TextField(blank=True, default='')),
                ('research1', models.TextField(blank=True, default='')),
                ('root_cause1', models.TextField(blank=True, default='')),
                ('present_state2', models.TextField(blank=True, default='')),
                ('desired_state2', models.TextField(blank=True, default='')),
                ('research2', models.TextField(blank=True, default='')),
                ('root_cause2', models.TextField(blank=True, default='')),
                ('present_state3', models.TextField(blank=True, default='')),
                ('desired_state3', models.TextField(blank=True, default='')),
                ('research3', models.TextField(blank=True, default='')),
                ('root_cause3', models.TextField(blank=True, default='')),
                ('present_state4', models.TextField(blank=True, default='')),
                ('desired_state4', models.TextField(blank=True, default='')),
                ('research4', models.TextField(blank=True, default='')),
                ('root_cause4', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
