# Generated by Django 5.0.6 on 2025-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rootcause_research1_alter_rootcause_research2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcause',
            name='desired_state5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='present_state5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='research5',
            field=models.TextField(blank=True, default='Why are labs necessary? Because...\nWhy...? Because...\nWhy...? Because...\nWhy...? Because...\nWhy...? Because...\n'),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='root_cause5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
