# Generated by Django 5.0.6 on 2025-07-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rootcause_desired_state5_rootcause_present_state5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowMightWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_might_we', models.TextField(blank=True, default='')),
                ('root_cause1', models.TextField(blank=True, default='')),
                ('hmw1', models.TextField(blank=True, default='How might we...')),
                ('rank1', models.TextField(blank=True, default='')),
                ('root_cause2', models.TextField(blank=True, default='')),
                ('hmw2', models.TextField(blank=True, default='How might we...')),
                ('rank2', models.TextField(blank=True, default='')),
                ('root_cause3', models.TextField(blank=True, default='')),
                ('hmw3', models.TextField(blank=True, default='How might we...')),
                ('rank3', models.TextField(blank=True, default='')),
                ('root_cause4', models.TextField(blank=True, default='')),
                ('hmw4', models.TextField(blank=True, default='How might we...')),
                ('rank4', models.TextField(blank=True, default='')),
                ('root_cause5', models.TextField(blank=True, default='')),
                ('hmw5', models.TextField(blank=True, default='How might we...')),
                ('rank5', models.TextField(blank=True, default='')),
                ('top_hmw1', models.TextField(blank=True, default='How might we...')),
                ('top_hmw2', models.TextField(blank=True, default='How might we...')),
                ('top_hmw3', models.TextField(blank=True, default='How might we...')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
