# Generated by Django 5.0.6 on 2025-07-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_solutionselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_desc', models.TextField(blank=True, default='')),
                ('f1_func_need', models.TextField(blank=True, default='')),
                ('f1_test_method', models.TextField(blank=True, default='')),
                ('f1_test_method_alt', models.TextField(blank=True, default='')),
                ('f1_emot_need', models.TextField(blank=True, default='')),
                ('f1_proto_test', models.TextField(blank=True, default='')),
                ('f1_who_test', models.TextField(blank=True, default='')),
                ('f1_where_test', models.TextField(blank=True, default='')),
                ('f1_proto_test_desc', models.TextField(blank=True, default='')),
                ('f1_proto_test_question', models.TextField(blank=True, default='')),
                ('f1_proto_test_satisfaction', models.TextField(blank=True, default='')),
                ('f2_desc', models.TextField(blank=True, default='')),
                ('f2_func_need', models.TextField(blank=True, default='')),
                ('f2_test_method', models.TextField(blank=True, default='')),
                ('f2_test_method_alt', models.TextField(blank=True, default='')),
                ('f2_emot_need', models.TextField(blank=True, default='')),
                ('f2_proto_test', models.TextField(blank=True, default='')),
                ('f2_who_test', models.TextField(blank=True, default='')),
                ('f2_where_test', models.TextField(blank=True, default='')),
                ('f2_proto_test_desc', models.TextField(blank=True, default='')),
                ('f2_proto_test_question', models.TextField(blank=True, default='')),
                ('f2_proto_test_satisfaction', models.TextField(blank=True, default='')),
                ('f3_desc', models.TextField(blank=True, default='')),
                ('f3_func_need', models.TextField(blank=True, default='')),
                ('f3_test_method', models.TextField(blank=True, default='')),
                ('f3_test_method_alt', models.TextField(blank=True, default='')),
                ('f3_emot_need', models.TextField(blank=True, default='')),
                ('f3_proto_test', models.TextField(blank=True, default='')),
                ('f3_who_test', models.TextField(blank=True, default='')),
                ('f3_where_test', models.TextField(blank=True, default='')),
                ('f3_proto_test_desc', models.TextField(blank=True, default='')),
                ('f3_proto_test_question', models.TextField(blank=True, default='')),
                ('f3_proto_test_satisfaction', models.TextField(blank=True, default='')),
                ('f4_desc', models.TextField(blank=True, default='')),
                ('f4_func_need', models.TextField(blank=True, default='')),
                ('f4_test_method', models.TextField(blank=True, default='')),
                ('f4_test_method_alt', models.TextField(blank=True, default='')),
                ('f4_emot_need', models.TextField(blank=True, default='')),
                ('f4_proto_test', models.TextField(blank=True, default='')),
                ('f4_who_test', models.TextField(blank=True, default='')),
                ('f4_where_test', models.TextField(blank=True, default='')),
                ('f4_proto_test_desc', models.TextField(blank=True, default='')),
                ('f4_proto_test_question', models.TextField(blank=True, default='')),
                ('f4_proto_test_satisfaction', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
