# Generated by Django 5.0.6 on 2025-07-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solutionvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_name', models.TextField(blank=True, default='')),
                ('c1_where_use', models.TextField(blank=True, default='')),
                ('c1_how_use', models.TextField(blank=True, default='')),
                ('c1_benefits', models.TextField(blank=True, default='')),
                ('c1_cost_risk', models.TextField(blank=True, default='')),
                ('c1_c_speed', models.TextField(blank=True, default='')),
                ('c1_o_speed', models.TextField(blank=True, default='')),
                ('c1_i_speed', models.TextField(blank=True, default='')),
                ('c2_name', models.TextField(blank=True, default='')),
                ('c2_where_use', models.TextField(blank=True, default='')),
                ('c2_how_use', models.TextField(blank=True, default='')),
                ('c2_benefits', models.TextField(blank=True, default='')),
                ('c2_cost_risk', models.TextField(blank=True, default='')),
                ('c2_c_speed', models.TextField(blank=True, default='')),
                ('c2_o_speed', models.TextField(blank=True, default='')),
                ('c2_i_speed', models.TextField(blank=True, default='')),
                ('c3_name', models.TextField(blank=True, default='')),
                ('c3_where_use', models.TextField(blank=True, default='')),
                ('c3_how_use', models.TextField(blank=True, default='')),
                ('c3_benefits', models.TextField(blank=True, default='')),
                ('c3_cost_risk', models.TextField(blank=True, default='')),
                ('c3_c_speed', models.TextField(blank=True, default='')),
                ('c3_o_speed', models.TextField(blank=True, default='')),
                ('c3_i_speed', models.TextField(blank=True, default='')),
                ('c4_name', models.TextField(blank=True, default='')),
                ('c4_where_use', models.TextField(blank=True, default='')),
                ('c4_how_use', models.TextField(blank=True, default='')),
                ('c4_benefits', models.TextField(blank=True, default='')),
                ('c4_cost_risk', models.TextField(blank=True, default='')),
                ('c4_c_speed', models.TextField(blank=True, default='')),
                ('c4_o_speed', models.TextField(blank=True, default='')),
                ('c4_i_speed', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
