# Generated by Django 5.0.6 on 2025-08-01 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_firstcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_problem1', models.TextField(blank=True, default='')),
                ('evidence_problem2', models.TextField(blank=True, default='')),
                ('evidence_problem3', models.TextField(blank=True, default='')),
                ('evidence_problem4', models.TextField(blank=True, default='')),
                ('evidence_novelty1', models.TextField(blank=True, default='')),
                ('evidence_novelty2', models.TextField(blank=True, default='')),
                ('evidence_novelty3', models.TextField(blank=True, default='')),
                ('evidence_novelty4', models.TextField(blank=True, default='')),
                ('evidence_feasible1', models.TextField(blank=True, default='')),
                ('evidence_feasible2', models.TextField(blank=True, default='')),
                ('evidence_feasible3', models.TextField(blank=True, default='')),
                ('evidence_feasible4', models.TextField(blank=True, default='')),
                ('evidence_viable1', models.TextField(blank=True, default='')),
                ('evidence_viable2', models.TextField(blank=True, default='')),
                ('evidence_viable3', models.TextField(blank=True, default='')),
                ('evidence_viable4', models.TextField(blank=True, default='')),
                ('creative_approach1', models.TextField(blank=True, default='')),
                ('creative_approach2', models.TextField(blank=True, default='')),
                ('creative_approach3', models.TextField(blank=True, default='')),
                ('creative_approach4', models.TextField(blank=True, default='')),
                ('first_customer1', models.TextField(blank=True, default='')),
                ('first_customer2', models.TextField(blank=True, default='')),
                ('first_customer3', models.TextField(blank=True, default='')),
                ('first_customer4', models.TextField(blank=True, default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
