# Generated by Django 5.0.6 on 2024-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_seed_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], default='PROCESSING', max_length=10),
        ),
    ]
