# Generated by Django 5.0.6 on 2024-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_seed_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='finetune_checkpoints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='finetune_metrics',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('SUMMARIZE-PROCESSING', 'Summarize Processing'), ('SUMMARIZE-FAILED', 'Summarize Failed'), ('UPLOADDATA-PROCESSING', 'Upload Data Processing'), ('UPLOADDATA-FAILED', 'Upload Data Failed'), ('FINETUNE-PROCESSING', 'Finetune Processing'), ('FINETUNE-FAILED', 'Finetune Failed'), ('FINETUNE-SUCCEEDED', 'Finetune Succeeded'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUMMARIZE-PROCESSING', max_length=100),
        ),
    ]
