# Generated by Django 5.0.6 on 2024-08-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0011_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
