# Generated by Django 5.0.6 on 2024-07-03 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_seed_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.advisor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.topic')),
            ],
        ),
    ]
