# Generated by Django 5.0.6 on 2024-07-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisee', '0001_initial'),
        ('advisor', '0002_seed_admin_and_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisee',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisor.advisor'),
        ),
    ]
