# Generated by Django 5.0.6 on 2024-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisee', '0003_seed_advisees'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisee',
            name='capitalization',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='competitive_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='content_marketing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='customer_journey',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='customer_lifetime_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='market_sizing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='networking',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='privacy_and_data_compliance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='product_market_fit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='saas_metrics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisee',
            name='valuation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
