# Generated by Django 5.0.6 on 2024-08-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisee', '0008_advisee_topic_instructions_advisee_topic_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisee',
            name='capitalization',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='competitive_analysis',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='content_marketing',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='customer_journey',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='customer_lifetime_value',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='market_sizing',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='networking',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='privacy_and_data_compliance',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='product_market_fit',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='saas_metrics',
        ),
        migrations.RemoveField(
            model_name='advisee',
            name='valuation',
        ),
    ]
